AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls',namespace='axf')),

]

app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.home,name='home'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.market,name='market'),
    url(r'^cart/', views.cart,name='cart'),
    url(r'^mine/', views.mine,name='mine'),
    url(r'^register/',views.register,name='register'),
    url(r'^logout/',views.exit,name='logout'),
    url(r'^login/',views.login,name='login'),
    url(r'^checkacc/',views.checkacc,name='checkacc'),
    url(r'^addtocart/',views.addtocart,name='addtocart'),
    url(r'^subcart/',views.subcart,name='subcart'),
    url(r'^changeselectstatus/',views.changeselectstatus,name='changeselectstatus'),
    url(r'^allselect/',views.allselect,name='allselect')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">

{#标题#}
{% block title %}
{% endblock %}

{#css样式#}
{% block EXTCSS %}
{% endblock %}
</head>
<body>
    {#头部#}
{% block header %}
    <header>爱鲜蜂</header>
{% endblock %}

{#内容#}
<div class="hidescroll">
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</div>
    {#尾部#}
{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt><span></span></dt>
                <dd> 首页</dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' 104749 0 0 %}" class="market">
            <dl>
                <dt><span></span></dt>
                <dd> 闪购超市</dd>
            </dl>
        </a>
        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt><span></span></dt>
                <dd> 购物车</dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt><span></span></dt>
                <dd> 我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}




<script src="{% static 'base/js/jquery.js' %}"></script>
<script src="{% static 'base/js/jquery.cookie.js' %}"></script>
<script src="{% static 'base/js/bootstrap.js' %}"></script>
<script src="{% static 'base/js/swiper.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>

{# JS脚本 #}
{% block EXTJS %}
{% endblock %}
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static%}

{% block EXTCSS %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}

{% block title %}
<title>购物车</title>
{% endblock %}

{% block content %}
    <div class="cart">
        <ul>
            {% for cart in carts %}
                <li>
                    <div class="confirm-wrapper" cartid="{{ cart.id }}" isselect="{{ cart.isselect }}">
                        {% if cart.isselect %}
                            <span class="glyphicon glyphicon-ok"></span>
                        {% else %}
                            <span class="no"></span>
                        {% endif %}
                    </div>
                    <div class="content-wrapper">
                        <div class="img">
                            <img src="{{ cart.goods.productimg }}">
                        </div>
                        <div class="detail">
                            <p class="name">{{ cart.goods.productlongname }}</p>
                            <p class="price">¥{{ cart.goods.price }}</p>
                            <p class="num">X{{ cart.goodnumber }}</p>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>

        <div class="bill">
            <div class="bill-left">
                <div class="all" isall="false">
                    <span class="no"></span>
                    <b>全选</b>
                </div>
                <div class="total">
                    <span>总计¥:</span>
                    <b>0</b>
                </div>
            </div>
            <div class="bill-right">
                计算(<span>0</span>)
            </div>
        </div>
    </div>
{% endblock %}

{% block EXTJS %}
    <script src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block EXTCSS %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}

{% block title %}
   <title>{{ title }}</title>
{% endblock %}

{% block content %}
{#    轮播图#}
    <div class="swiper-container" id="topSwiper">
        <div class="swiper-wrapper">
            {% for wheel in wheels %}
                <div class="swiper-slide">
                    <img src="{{ wheel.img }}" alt="{{ wheel.name }}">
                </div>
            {% endfor %}
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>

    </div>
{#     导航#}
    <div class="nav">
        <ul>
            {% for nav in navs %}
                <li>
                    <a href="#">
                        <img src="{{ nav.img }}" alt="">
                        <span>{{ nav.name }}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{#    每日必购#}
    <div class="swiper-container" id="mustbuySwiper">
        <div class="swiper-wrapper">
            {% for mustbuy in mustbuys %}
                <div class="swiper-slide">
                    <a href="#">
                        <img src="{{ mustbuy.img }}" alt="{{ mustbuy.name }}">
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{#商品部分#}
    <div class="shop">
        <div class="shophead">
            <a href="#">
                <img src="{{ shophead.img }}">
            </a>
        </div>

        <div class="shoptab">
            {% for shoptab in shoptabs %}
                <a href="#">
                    <img src="{{ shoptab.img }}">
                </a>
            {% endfor %}

        </div>

        <div class="shopclass">
                {% for shopclass in shopclasss %}
                    <li>
                        <a>
                            <img src="{{ shopclass.img }}">
                        </a>
                    </li>
                {% endfor %}
        </div>

        <div class="shopcommend">
            {% for shopcommend in shopcommends %}
                <li>
                    <a href="#">
                        <img src="{{ shopcommend.img }}">
                    </a>
                </li>
            {% endfor %}

        </div>
    </div>

{#    商品主体#}
    <div class="main">
        {% for mainshow in mainshows %}
            <div class="main-wrapper">
                <div class="title">
                    {{ mainshow.name }}
                    <a href="#">更多</a>
                    <span></span>
                </div>
                <div class="headimg">
                    <img src="{{ mainshow.img }}">
                </div>
                <div class="shoplist">
                    <div class="shopitem">
                        <a href="#">
                            <img class="img" src="{{ mainshow.img1 }}">
                            <div class="desc">{{ mainshow.longname1 }}</div>
                            <div class="price">{{ mainshow.price1 }}</div>
                            <div class="marketprice">{{ mainshow.marketprice1 }}</div>

                        </a>
                        <button><span>+</span></button>
                    </div>
                    <div class="shopitem">
                        <a href="#">
                            <img class="img" src="{{ mainshow.img2 }}">
                            <div class="desc">{{ mainshow.longname2 }}</div>
                            <div class="price">{{ mainshow.price2 }}</div>
                            <div class="marketprice">{{ mainshow.marketprice2 }}</div>
                        </a>
                        <button><span>+</span></button>
                    </div>
                    <div class="shopitem">
                        <a href="#">
                            <img class="img" src="{{ mainshow.img3 }}">
                            <div class="desc">{{ mainshow.longname3 }}</div>
                            <div class="price">{{ mainshow.price3 }}</div>
                            <div class="marketprice">{{ mainshow.marketprice3 }}</div>
                        </a>
                        <button><span>+</span></button>

                    </div>
                </div>
            </div>
        {% endfor %}

    </div>

{% endblock %}

{% block EXTJS %}
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static%}

{% block EXTCSS %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}

{% block title %}
<title>登录</title>
{% endblock %}

{% block content %}
    <div class="login">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>

        <form action="{% url 'axf:login' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <span class="err">{{ error }}</span>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">账号</span>
            <input type="text" class="form-control" placeholder="6~12个字符" aria-describedby="basic-addon1" name="account">
        </div>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">密码</span>
            <input type="password" class="form-control" placeholder="6~12个字符" aria-describedby="basic-addon1" name="password">
        </div>
            <input type="submit" value="登录" class="btn btn-primary" id="btn1">
    </form>
    </div>
{% endblock %}

{% block EXTJS %}
    <script>
        $(function () {
            $('.login').width(innerWidth)
        })
    </script>
{% endblock %}

templates/market.html
{% extends 'base.html' %}
{% load static%}

{% block EXTCSS %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block content %}
<div class="market">
{#    左部列表#}
    <div class="type-slider">
        <ul>
            {% for foodtype in foodtypes %}
                <li>
                    <span></span>
                    <a href="{% url 'axf:market' foodtype.typeid childid 0 %}">{{ foodtype.typename }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{#    顶部导航#}
    <nav>
        <ul>
            <li><span id="allbt">全部分类<i class="glyphicon glyphicon-chevron-up"></i></span></li>
            <li><span id="sortbt">综合排序<i class="glyphicon glyphicon-chevron-up"></i></span></li>
        </ul>
    </nav>
{#主体商品#}
    <div class="main-content">
{#    商品#}
        <div class="content-wrapper">
            <ul>
                {% for good in goodlist %}
                    <li>
                        <a href="#">
                            <img  class="goods-img" src="{{ good.productimg }}" alt="">
                            <div class="goods-info">
                                <p class="name">{{ good.productlongname }}</p>
                                <p class="detailtag">
                                    {% if good.isxf %}
                                        <span class="xf">精选</span>
                                    {% endif %}
                                </p>
                                <p class="specifics">{{ good.specifics }}</p>
                                <p class="price">
                                    <i class="now-price">{{ good.price }}</i>
                                    <i class="market-price">{{ good.marketprice }}</i>
                                </p>
                            </div>
                        </a>
                        <div class="bt-wrapper">
                            <span class="glyphicon glyphicon-minus" goodid="{{ good.id }}" ></span>
                            <span class="num">
                                {% for cart in carts %}
                                    {% if cart.goods_id == good.id %}
                                        {{ cart.goodnumber }}
                                    {% endif %}
                                {% endfor %}
                            </span>
                            <span class="glyphicon glyphicon-plus" goodid="{{ good.id }}"></span>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
{#    子类菜单#}
{#    全部类别#}
        <div class="bounce-view" id="childview">
            <div class="bounce-wrapper">
                {% for child in chlist %}
                    <a href="{% url 'axf:market' categoryid child.chid 0 %}">
                        {{ child.chname }}
                    </a>
                {% endfor %}
            </div>
        </div>
        <div class="bounce-view" id="sortview">
            <div class="bounce-wrapper">
                <a href="{% url 'axf:market' categoryid childid 0 %}">综合排序</a>
                <a href="{% url 'axf:market' categoryid childid 1 %}">销量排序</a>
                <a href="{% url 'axf:market' categoryid childid 2 %}">价格最低</a>
                <a href="{% url 'axf:market' categoryid childid 3 %}">价格最高</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block EXTJS %}
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}

templates/mine.html
{% extends 'base.html' %}
{% load static%}

{% block EXTCSS %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}

{% block title %}
<title>我的</title>
{% endblock %}

{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <img src="{{ img }}" alt="">
            </div>
            <div class="user-content">
               <p><span class="glyphicon glyphicon-user"></span><a href="{% url 'axf:login' %}">{{ name }}</a></p>
                <p><span class="glyphicon glyphicon-fire"></span>svip{{ rank }}</p>
                <div class="register"><a href="{% url 'axf:register' %}">注册</a></div>
            </div>
        </div>
    
        <div class="collect">
            <span class="glyphicon glyphicon-heart"></span>
            <span>商品收藏</span>
        </div>
    
        <div class="other">
            <section class="my">
                <span>我的订单</span>
                <a href="#">查看全部订单<i class="glyphicon glyphicon-chevron-right"></i></a>
            </section>
            <section>
                <ul>
                    <li>
                        <dl>
                            <dt>
                            <dd class="glyphicon glyphicon-usd"></dd>
                            <dd>待付款</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                            <dd class="glyphicon glyphicon-check"></dd>
                            <dd>待收货</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                            <dd class="glyphicon glyphicon-comment"></dd>
                            <dd>待评价</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                            <dd class="glyphicon glyphicon-send"></dd>
                            <dd>退款/售后</dd>
                            </dt>
                        </dl>
                    </li>
                </ul>
            </section>
            <section>
                <ul>
                    <li>
                        <dl>
                            <dt>
                            <dd class="glyphicon glyphicon-credit-card"></dd>
                            <dd>优惠券</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                            <dd class="glyphicon glyphicon-home"></dd>
                            <dd>收货地址</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                            <dd class="glyphicon glyphicon-phone-alt"></dd>
                            <dd>客服/反馈</dd>
                            </dt>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                            <dd class="glyphicon glyphicon-tasks"></dd>
                            <dd>关于我们</dd>
                            </dt>
                        </dl>
                    </li>
                </ul>
            </section>

           {% if login %}
                <section>
                    <div class="quit">
                        <a href="{% url 'axf:logout' %}">退出登录</a>
                    </div>
                </section>
           {% endif %}
        </div>
    </div>
{% endblock %}

{% block EXTJS %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static%}

{% block EXTCSS %}
    <link rel="stylesheet" href="{% static 'mine/css/register.css' %}">
{% endblock %}

{% block title %}
<title>注册</title>
{% endblock %}

{% block content %}
    <div class="register">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>

        <form action="{% url 'axf:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">账号</span>
            <input type="text" class="form-control" placeholder="6~12个字符" aria-describedby="basic-addon1" name="account" id="account">
        </div>
        <span class="error" id="acc"></span>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">密码</span>
            <input type="password" class="form-control" placeholder="6~12个字符" aria-describedby="basic-addon1" name="password" id="password">
        </div>
        <span class="error" id="psd"></span>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">验证</span>
            <input type="password" class="form-control" placeholder="6~12个字符" aria-describedby="basic-addon1" name="mypassword" id="mypassword">
        </div>
        <span class="error" id="mypsd"></span>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">昵称</span>
            <input type="text" class="form-control"  aria-describedby="basic-addon1" name="name">
        </div>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">电话</span>
            <input type="text" class="form-control"  aria-describedby="basic-addon1" name="tel">
        </div>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">地址</span>
            <input type="text" class="form-control"  aria-describedby="basic-addon1" name="address">
        </div>
        <div class="form-group">
{#            <label for="exampleInputFile">File input</label>#}
            <input type="file" id="exampleInputFile" name="img">
        </div>
        <input type="submit" value="注册" class="btn btn-primary" id="subButton">
    </form>
    </div>
{% endblock %}

{% block EXTJS %}
    <script>
        $(function () {
            $('.register').width(innerWidth)
        })
    </script>
    <script src="{% static 'mine/js/registe.js' %}"></script>
{% endblock %}